import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: 'Richieste di funzionalità',
  filterNew: 'Nuovo',
  filterPlanned: 'Pianificato',
  filterInProgress: 'In corso',
  filterDone: 'Completato',
  titlePlaceholder: 'Titolo della funzionalità',
  descriptionPlaceholder: 'Descrivi la funzionalità...',
  submit: 'Invia',
  cancel: 'Annulla',
  emailPlaceholder: 'Il tuo indirizzo email',
  emailEncouragement: 'Aggiungi la tua email per ricevere aggiornamenti',
  emailRequired: 'L\'email è obbligatoria',
  empty: 'Nessuna richiesta ancora',
  emptyHint: 'Sii il primo a suggerire una funzionalità!',
  error: 'Qualcosa è andato storto',
  retry: 'Riprova',
  comments: 'Commenti',
  commentsCount: '{count} commenti',
  noComments: 'Ancora nessun commento',
  noCommentsHint: 'Sii il primo a condividere la tua opinione',
  commentPlaceholder: 'Scrivi un commento...',
  postComment: 'Pubblica',
  developerBadge: 'Sviluppatore',
  pendingReview: 'In attesa di revisione',
  badgePlanned: 'Pianificato',
  newRequest: 'Nuova richiesta',
};
