import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: 'Functieverzoeken',
  filterNew: 'Nieuw',
  filterPlanned: 'Gepland',
  filterInProgress: 'In uitvoering',
  filterDone: 'Voltooid',
  titlePlaceholder: 'Functietitel',
  descriptionPlaceholder: 'Beschrijf de functie...',
  submit: 'Verzenden',
  cancel: 'Annuleren',
  emailPlaceholder: 'Je e-mailadres',
  emailEncouragement: 'Voeg je e-mail toe zodat we je kunnen bereiken',
  emailRequired: 'E-mail is verplicht',
  empty: 'Nog geen functieverzoeken',
  emptyHint: 'Wees de eerste die een functie voorstelt!',
  error: 'Er is iets misgegaan',
  retry: 'Opnieuw proberen',
  comments: 'Reacties',
  commentsCount: '{count} reacties',
  noComments: 'Nog geen reacties',
  noCommentsHint: 'Wees de eerste die reageert',
  commentPlaceholder: 'Schrijf een reactie...',
  postComment: 'Plaatsen',
  developerBadge: 'Ontwikkelaar',
  pendingReview: 'Wacht op beoordeling',
  badgePlanned: 'Gepland',
};
